function Other() {
    return (
        <div class='other'>
            <h3>Other</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec rutrum nisi consectetur porta vestibulum. Ut at laoreet urna. Praesent nec justo et risus condimentum dignissim. Nullam porttitor, felis sit amet egestas egestas, mi tortor consectetur sapien, sit amet consectetur est purus nec lorem. Aenean finibus pharetra massa. In ultrices varius ante, a viverra ex egestas nec. Morbi at nunc massa. Praesent nec enim arcu. Nam ultrices pretium accumsan. Morbi interdum bibendum felis, in sagittis urna sodales vel.</p>
            <p>Cras non mattis elit. Etiam condimentum porta neque. Pellentesque eget turpis eu justo accumsan euismod rhoncus venenatis nibh. Integer placerat elementum nisl, sit amet tincidunt lorem elementum pellentesque. Sed cursus nunc sit amet ipsum venenatis malesuada. Curabitur pretium mauris ut sem vehicula, ac fringilla mauris maximus. Sed dictum dui a nunc dignissim maximus. Praesent libero lectus, ornare et ultrices at, volutpat et diam. Fusce eros erat, consequat quis magna eget, dapibus iaculis est. Quisque tempor elit a velit finibus, nec ullamcorper erat vulputate. Aliquam eget tortor nec neque fermentum pellentesque.</p>
            <p>In hac habitasse platea dictumst. Aenean mauris neque, hendrerit gravida porttitor ut, semper sit amet leo. Duis fermentum diam a eros dapibus egestas. Nullam nulla turpis, fermentum vehicula sapien tincidunt, bibendum condimentum sapien. Nullam quis risus faucibus, bibendum lacus sed, pulvinar sapien. In nec diam urna. Pellentesque eros neque, rhoncus vel tempor quis, semper non augue. Maecenas mollis tincidunt urna pharetra ullamcorper. Cras interdum luctus arcu non tempus. Pellentesque malesuada ipsum quis convallis ullamcorper. Ut placerat elementum auctor. Sed vestibulum est ut mi pulvinar egestas sit amet sit amet urna. Aliquam sagittis bibendum libero non maximus. Integer libero eros, tempus ultrices dui nec, congue sagittis felis.</p>
            <p>Nunc porttitor interdum semper. Proin dictum efficitur est quis sodales. Vivamus mi sapien, sagittis dignissim blandit ut, interdum et dolor. Cras placerat erat sit amet purus consectetur, ac scelerisque ipsum sollicitudin. Aliquam ante est, vehicula sed eros congue, mattis eleifend ante. Donec congue tortor rutrum ipsum aliquet eleifend. Vestibulum laoreet est ut libero eleifend rutrum.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec rutrum nisi consectetur porta vestibulum. Ut at laoreet urna. Praesent nec justo et risus condimentum dignissim. Nullam porttitor, felis sit amet egestas egestas, mi tortor consectetur sapien, sit amet consectetur est purus nec lorem. Aenean finibus pharetra massa. In ultrices varius ante, a viverra ex egestas nec. Morbi at nunc massa. Praesent nec enim arcu. Nam ultrices pretium accumsan. Morbi interdum bibendum felis, in sagittis urna sodales vel.</p>
            <p>Cras non mattis elit. Etiam condimentum porta neque. Pellentesque eget turpis eu justo accumsan euismod rhoncus venenatis nibh. Integer placerat elementum nisl, sit amet tincidunt lorem elementum pellentesque. Sed cursus nunc sit amet ipsum venenatis malesuada. Curabitur pretium mauris ut sem vehicula, ac fringilla mauris maximus. Sed dictum dui a nunc dignissim maximus. Praesent libero lectus, ornare et ultrices at, volutpat et diam. Fusce eros erat, consequat quis magna eget, dapibus iaculis est. Quisque tempor elit a velit finibus, nec ullamcorper erat vulputate. Aliquam eget tortor nec neque fermentum pellentesque.</p>
            <p>In hac habitasse platea dictumst. Aenean mauris neque, hendrerit gravida porttitor ut, semper sit amet leo. Duis fermentum diam a eros dapibus egestas. Nullam nulla turpis, fermentum vehicula sapien tincidunt, bibendum condimentum sapien. Nullam quis risus faucibus, bibendum lacus sed, pulvinar sapien. In nec diam urna. Pellentesque eros neque, rhoncus vel tempor quis, semper non augue. Maecenas mollis tincidunt urna pharetra ullamcorper. Cras interdum luctus arcu non tempus. Pellentesque malesuada ipsum quis convallis ullamcorper. Ut placerat elementum auctor. Sed vestibulum est ut mi pulvinar egestas sit amet sit amet urna. Aliquam sagittis bibendum libero non maximus. Integer libero eros, tempus ultrices dui nec, congue sagittis felis.</p>
            <p>Nunc porttitor interdum semper. Proin dictum efficitur est quis sodales. Vivamus mi sapien, sagittis dignissim blandit ut, interdum et dolor. Cras placerat erat sit amet purus consectetur, ac scelerisque ipsum sollicitudin. Aliquam ante est, vehicula sed eros congue, mattis eleifend ante. Donec congue tortor rutrum ipsum aliquet eleifend. Vestibulum laoreet est ut libero eleifend rutrum.</p>
        </div>
    )
}

export default Other;